 baseURL = "https://BCBuizer.github.io/"
 languageCode = "en-us"
 theme = "anatole"
 enableEmoji = true

 [params]
 title = "Power Platform Community Solutions"
 description = "Answers to recurring questions"
 mainSections = ["blog"]
 author = "BCBuizer"
 profilePicture = "images/profile_pic.png"

 [[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/barend-buizer/"

[[params.socialIcons]]
icon = "fas fa-light fa-users"
title = "Microsoft Power Platform Community"
url = "https://powerusers.microsoft.com/t5/user/viewprofilepage/user-id/266500/"